
CREATE TABLE IF NOT EXISTS `persona` (
  `CODPERSO` char(20) NOT NULL DEFAULT '',
  `NOMBPERSO` varchar(50) DEFAULT NULL,
  `APELLIPERSO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CODPERSO`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `usuario` (
  `usu` char(20) NOT NULL DEFAULT '',
  `cla` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`usu`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `persona`
--
INSERT INTO `usuario` (`usu`, `cla`) VALUES('etolentino','123');

INSERT INTO `persona` (`CODPERSO`, `NOMBPERSO`, `APELLIPERSO`) VALUES
('1', 'IVAN', 'VERA'),
('2', 'LARISSA', 'VERA'),
('3', 'ALBERTO', 'PETRLIK'),
('4', 'ANDRES', 'PETRLIK'),
('5', 'ANA', 'QUISPE'),
('6', 'JUAN', 'QUISPE'),
('7', 'PEDRO', 'PETRLIK'),
('8', 'JUANA', 'PETRLIK');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
